import test from 'node:test';import assert from 'node:assert/strict';
import {createFinishNotificationController} from './finishNotifications.js';
const state=enabled=>({schema_version:'infergrade.desktop_notifications.v1',enabled,available:true,warning:null});
test('finish notifications stay off after read and do not send while off or disconnected',async()=>{let writes=0,notices=0;const c=createFinishNotificationController({read:async()=>state(false),write:async()=>{writes++;return state(true);},notify:async()=>{notices++;return{submitted:true};},render:()=>{}});await c.refresh();await c.completed('run_one');c.setConnectionKey('runnerA');await c.completed('run_one');assert.equal(writes,0);assert.equal(notices,0);await c.setEnabled(true);await c.completed('run_one');await c.completed('run_one');assert.equal(notices,1);});
test('finish notification requests coalesce and discard errors from old connections',async()=>{let reject,notices=0,rendered;const c=createFinishNotificationController({read:async()=>state(true),write:async()=>state(true),notify:()=>{notices++;return new Promise((resolve,r)=>{reject=r;});},render:value=>{rendered=value;}});await c.refresh();c.setConnectionKey('runnerA');const pending=c.completed('run_one');await c.completed('run_one');assert.equal(notices,1);c.setConnectionKey('runnerB');reject(new Error('private old connection'));await pending;assert.equal(rendered.noticeError,null);});
test('notification write failure retains confirmed state and blocks unconfirmed values',async()=>{let rendered;const c=createFinishNotificationController({read:async()=>state(false),write:async()=>{throw Error('write failed');},notify:async()=>({submitted:true}),render:value=>{rendered=value;}});await c.refresh();await c.setEnabled(true);assert.equal(rendered.state.enabled,false);assert.match(rendered.error,/Retry/);});

test('completion during preference refresh waits for confirmation',async()=>{let resolve,notices=0;const c=createFinishNotificationController({read:()=>new Promise(r=>{resolve=r;}),write:async()=>state(true),notify:async()=>{notices++;return{submitted:true};},render:()=>{}});c.setConnectionKey('runnerA');const refresh=c.refresh();await c.completed('run_one');assert.equal(notices,0);resolve(state(true));await refresh;await new Promise(r=>setTimeout(r,0));assert.equal(notices,1);});
test('connection changes do not clear unconfirmed preference errors',async()=>{let rendered,notices=0;const c=createFinishNotificationController({read:async()=>state(true),write:async()=>{throw Error();},notify:async()=>{notices++;return{submitted:true};},render:value=>{rendered=value;}});await c.refresh();await c.setEnabled(false);c.setConnectionKey('runnerB');assert.ok(rendered.error);await c.completed('run_one');assert.equal(notices,0);});
