import test from 'node:test';
import assert from 'node:assert/strict';
import {createPrivateBenchmarkController} from './privateBenchmark.js';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
const setup=overrides=>{const renders=[];const controller=createPrivateBenchmarkController({start:async()=>({status:'running',pid:42}),stop:async()=>({status:'stop_requested'}),status:async()=>({status:'idle',pid:null}),history:async()=>({schema_version:'infergrade.private_history.v1',results:[],unreadable_count:0}),openReport:async()=>{},render:value=>renders.push(value),...overrides});return{controller,renders};};
test('coalesces start and never treats rejected admission as running',async()=>{const wait=deferred();let calls=0;const{controller,renders}=setup({start:()=>{calls++;return wait.promise;}});const first=controller.start({modelPath:'local'});assert.equal(await controller.start({}),false);assert.equal(calls,1);wait.reject(new Error('Stop listening first.'));assert.equal(await first,false);assert.equal(renders.at(-1).current.status,'idle');assert.match(renders.at(-1).error,/Stop listening/);});
test('old idle poll cannot erase a new private process',async()=>{const wait=deferred();const{controller,renders}=setup({status:()=>wait.promise});const poll=controller.refresh();assert.equal(await controller.start({}),true);wait.resolve({status:'idle',pid:null});await poll;assert.equal(renders.at(-1).current.pid,42);assert.equal(renders.at(-1).current.status,'running');});
test('stop targets exact confirmed PID and waits for terminal receipt',async()=>{const targets=[];const{controller,renders}=setup({stop:async pid=>{targets.push(pid);return{status:'stop_requested'};},status:async()=>({status:'failed',pid:42,phase:'Interrupted'})});await controller.start({});await controller.stop();assert.deepEqual(targets,[42]);assert.equal(renders.at(-1).current.status,'running');await controller.refresh();assert.equal(renders.at(-1).current.status,'failed');});
test('private history preserves canonical null headline and component results',async()=>{const row={id:'private_a',score:null,component_scores:{ifeval:0.4},status:'completed'};const{controller,renders}=setup({history:async()=>({schema_version:'infergrade.private_history.v1',results:[row],unreadable_count:0})});await controller.refreshHistory();assert.equal(renders.at(-1).rows[0].score,null);assert.deepEqual(renders.at(-1).rows[0].component_scores,{ifeval:0.4});});
test('report failures stay local and do not restart or publish work',async()=>{let starts=0;const{controller,renders}=setup({start:async()=>{starts++;},openReport:async()=>{throw new Error('unavailable');}});await controller.openReport('private_a');assert.equal(starts,0);assert.match(renders.at(-1).error,/local report/);});

test('held history response cannot overwrite new-start state or error',async()=>{const wait=deferred();const{controller,renders}=setup({history:()=>wait.promise});const history=controller.refreshHistory();await controller.start({});wait.reject(new Error('old history'));await history;assert.equal(renders.at(-1).current.pid,42);assert.equal(renders.at(-1).error,null);assert.equal(renders.at(-1).historyPending,false);});

test('lost start acknowledgement discovers supervised process before enabling retry',async()=>{const{controller,renders}=setup({start:async()=>{throw new Error('lost acknowledgement');},status:async()=>({status:'running',pid:84})});assert.equal(await controller.start({}),true);assert.equal(renders.at(-1).current.pid,84);assert.equal(await controller.start({}),false);});
test('unconfirmed start keeps a recovery panel and polls rather than permitting duplicate start',async()=>{const{controller,renders}=setup({start:async()=>{throw new Error('lost acknowledgement');},status:async()=>{throw new Error('unavailable');}});assert.equal(await controller.start({}),false);assert.equal(renders.at(-1).current.status,'unconfirmed');assert.equal(controller.isRunning(),true);assert.equal(await controller.start({}),false);});
