const componentLabels={ifeval:'IFEval',assistant_compositional_instruction_v2:'Compositional instructions',multiturn_chat_memory_v1:'Chat memory',coding_static_repair_v1:'Static code repair',reasoning_exact_answer_v1:'Exact reasoning answers'};
export function createPrivateBenchmarkController({start,stop,status,history,openReport,render}){
 let current={status:'idle',pid:null},rows=[],pending=false,error=null,generation=0,reading=false,historyPending=false,historySequence=0;
 const show=()=>render({current,rows,pending,historyPending,error});
 const refreshHistory=async()=>{if(current.status==='running'||historyPending)return;const own=generation,sequence=++historySequence;historyPending=true;show();try{const value=await history();if(own!==generation||sequence!==historySequence)return;if(value?.schema_version!=='infergrade.private_history.v1'||!Array.isArray(value.results))throw new Error();rows=value.results;error=value.unreadable_count?'Some local reports could not be read. Check local storage.':null;}catch{if(own===generation&&sequence===historySequence)error='Could not read private history. Refresh after checking local storage.';}finally{if(sequence===historySequence){historyPending=false;show();}}};
 const refresh=async()=>{if(reading)return;reading=true;const own=generation;try{const value=await status();if(!['idle','running','completed','failed'].includes(value?.status))throw new Error();if(own!==generation)return;const was=current.status;current=value;if(value.status!=='running'&&was!==value.status)await refreshHistory();show();}catch{if(own===generation){error='Could not confirm private work. Keep Runner open and refresh.';show();}}finally{reading=false;}};
 return{
  refresh,refreshHistory,repaint:show,isRunning:()=>['running','unconfirmed'].includes(current.status),
  start:async(input)=>{if(pending||['running','unconfirmed'].includes(current.status))return false;let started=false;pending=true;error=null;++generation;show();try{const value=await start(input);if(value?.status!=='running'||!Number.isInteger(value.pid))throw new Error('Private benchmark did not return a process identity.');current=value;started=true;}catch(e){error=typeof e==='string'?e:e?.message||'Could not start a private benchmark. Check the installed runtime and stop listening.';try{const confirmed=await status();if(!['idle','running','completed','failed'].includes(confirmed?.status))throw new Error();current=confirmed;if(confirmed.status==='running'){started=true;error=null;}}catch{current={status:'unconfirmed',pid:null,phase:'Confirm whether private work started. Keep Runner open and refresh.'};}}finally{pending=false;show();}return started;},
  stop:async()=>{if(pending||current.status!=='running'||!Number.isInteger(current.pid))return;pending=true;error=null;show();try{await stop(current.pid);current={...current,phase:'Stop requested. Waiting for process cleanup.'};}catch{error='Could not request Stop. Keep Runner open and try again.';}finally{pending=false;show();}},
  openReport:async(id)=>{try{await openReport(id);}catch{error='Could not open the local report. Refresh private history.';show();}}
 };
}
export function initPrivateBenchmark({invoke,onRun=()=>{}}){
 const models=document.querySelector('[data-desktop-view="models"]'),activity=document.querySelector('[data-desktop-view="activity"]'),home=document.querySelector('[data-desktop-view="home"]');if(!models||!activity||!home)return null;
 const panel=document.createElement('section');panel.className='drawer-panel desktop-private-benchmark';panel.innerHTML='<h2 tabindex="-1">Benchmark a local file privately</h2><p>The report stays on this machine. Choose a use case and depth, then stop listening before starting.</p><label>Local GGUF file<input data-private-path readonly placeholder="Choose a file from Found on this machine"></label><label>Use case<select data-private-use-case><option value="general_assistant">Chat and instructions</option><option value="agentic_coding">Coding · static repair only</option><option value="reasoning">Reasoning · exact answers only</option></select></label><label>Depth<select data-private-tier><option value="canary">Canary · small sample</option><option value="standard">Standard · larger sample</option></select></label><p class="desktop-sub">This uses installed llama.cpp and Runner checks. Coding and reasoning cover part of their use case; the report shows missing coverage. Memory fit and compatibility are checked by the runtime.</p><button type="button" class="button-primary" data-private-start disabled>Start private benchmark</button><p data-private-error role="status"></p>';
 models.append(panel);
 const runPanel=document.createElement('section');runPanel.className='drawer-panel desktop-private-running';runPanel.hidden=true;runPanel.innerHTML='<h2>Private benchmark</h2><p data-private-phase role="status"></p><button type="button" class="button-secondary" data-private-stop>Stop private benchmark</button><button type="button" class="button-secondary" data-private-status>Refresh private work</button><p>Keep this machine awake. Nothing is uploaded to Hub.</p>';home.append(runPanel);
 const historyPanel=document.createElement('section');historyPanel.className='drawer-panel desktop-private-history';historyPanel.innerHTML='<h2>Private on this machine</h2><p role="status" data-private-history-status>Checking local reports…</p><div data-private-history-list></div><button type="button" class="button-secondary" data-private-history-refresh>Refresh private history</button>';activity.append(historyPanel);
 const path=panel.querySelector('[data-private-path]'),startButton=panel.querySelector('[data-private-start]'),stopButton=runPanel.querySelector('[data-private-stop]'),error=panel.querySelector('[data-private-error]'),list=historyPanel.querySelector('[data-private-history-list]');
 const call=async(command,args)=>{const transport=await invoke();if(!transport)throw new Error('Open the desktop app to benchmark a local file.');return transport(command,args);};
 let lastRows=null;
 const controller=createPrivateBenchmarkController({start:args=>call('start_desktop_private_benchmark',args),stop:expectedPid=>call('stop_desktop_private_benchmark',{expectedPid}),status:()=>call('desktop_private_benchmark_status'),history:()=>call('desktop_private_benchmark_history'),openReport:id=>call('open_desktop_private_report',{id}),render:({current,rows,pending,historyPending,error:message})=>{
  startButton.disabled=pending||historyPending||['running','unconfirmed'].includes(current.status)||!path.value;stopButton.disabled=pending||current.status!=='running';error.textContent=message||'';runPanel.hidden=current.status==='idle';runPanel.querySelector('[data-private-phase]').textContent=message||current.phase||current.status;historyPanel.querySelector('[data-private-history-refresh]').disabled=historyPending;
  historyPanel.querySelector('[data-private-history-status]').textContent=message||(rows.length?`${rows.length} local report${rows.length===1?'':'s'}.`:'No private benchmarks yet.');
  if(rows===lastRows)return;lastRows=rows;const focusedId=document.activeElement?.dataset.privateReportId;list.replaceChildren();
  for(const row of rows){const item=document.createElement('div');item.className='private-history-row';const title=document.createElement('strong');title.textContent=row.model_filename;const details=document.createElement('p');details.textContent=`${row.status==='running'?'Unfinished':row.status==='completed'?(row.capability_status==='partial'?'Finished · partial checks':'Finished'):'Did not finish'} · ${row.tier==='canary'?'Small sample':'Standard'} · ${new Date(row.created_at).toLocaleString()} · private`;item.append(title,details);const scores=document.createElement('p');if(Number.isFinite(row.score))scores.textContent=`Capability score ${(row.score*100).toFixed(1)} / 100`;else{const parts=Object.entries(row.component_scores||{}).filter(([,v])=>Number.isFinite(v)).map(([name,value])=>`${componentLabels[name]||name}: ${(value*100).toFixed(1)}%`);scores.textContent=parts.length?`Component results · ${parts.join(' · ')}. Headline score unavailable.`:'See the local report for execution details.';}item.append(scores);if(row.report_available){const button=document.createElement('button');button.type='button';button.className='button-secondary';button.textContent='Open local report';button.dataset.privateReportId=row.id;button.onclick=()=>controller.openReport(row.id);item.append(button);}list.append(item);}
  if(focusedId)[...list.querySelectorAll('button')].find(button=>button.dataset.privateReportId===focusedId)?.focus();
 }});
 startButton.onclick=async()=>{const started=await controller.start({modelPath:path.value,useCase:panel.querySelector('[data-private-use-case]').value,tier:panel.querySelector('[data-private-tier]').value});if(started)onRun();};stopButton.onclick=()=>controller.stop();runPanel.querySelector('[data-private-status]').onclick=()=>controller.refresh();historyPanel.querySelector('[data-private-history-refresh]').onclick=()=>controller.refreshHistory();
 controller.refresh().then(()=>controller.refreshHistory());window.setInterval(()=>{if(controller.isRunning())controller.refresh();},1500);
 return{chooseFile:value=>{path.value=value;panel.querySelector('h2').focus();panel.scrollIntoView({block:'start'});controller.repaint();},controller};
}
